type Category {
    categoryId: ID!
    categoryName: String!
    icon: String
}

type Product {
    productId: ID!
    productName: String!
    unitPrice: Float!
    quantity: Int!
    description: String
    images: String
    discount: Float
    status: Int
    category: Category
}

type ProductPage {
    content: [Product]
    totalPages: Int
    totalElements: Int
    pageNumber: Int
}

type CategoryPage {
    content: [Category]
    totalPages: Int
    totalElements: Int
    pageNumber: Int
}

input ProductInput {
    productName: String!
    unitPrice: Float!
    quantity: Int!
    description: String
    images: String
    discount: Float
    status: Int
    categoryId: ID!
}

input CategoryInput {
    categoryName: String!
    icon: String
}

type Query {
    productsByPriceAsc: [Product]

    productsByCategory(categoryId: ID!): [Product]

    productsPage(keyword: String, categoryId: ID, page: Int, size: Int): ProductPage
    productById(id: ID!): Product

    categoriesPage(keyword: String, page: Int, size: Int): CategoryPage
    allCategories: [Category]
    categoryById(id: ID!): Category
}

type Mutation {
    # CRUD Category
    createCategory(input: CategoryInput!): Category
    updateCategory(id: ID!, input: CategoryInput!): Category
    deleteCategory(id: ID!): Boolean

    # CRUD Product
    createProduct(input: ProductInput!): Product
    updateProduct(id: ID!, input: ProductInput!): Product
    deleteProduct(id: ID!): Boolean
}